# Site settings
title: Halo9Pan
description: Resume for HaloPan
favicon: /assets/img/avatar.jpg
baseurl:
url: http://cv.halo9pan.info
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  name: Halo Pan
  title: Data Painters, Cloud Artificer, Full-stack Programmer, Intelligent Practitioner......
  address: Beijing
  email: me@halo9pan.info
  mail: halo9pan@hotmail.com
  link: http://halo9pan.info
  github: Halo9Pan
  weibo: halo9pan
  qq: 104349832
  linkedin: Halo9Pan
  twitter: Halo9Pan
  facebook: Halo9Pan
  gavatar: /assets/img/avatar.jpg
  works:
    - work1:
      company: iQIYI.com
      department: Technology and Product Center
      section: Backend Development
      location: Beijing
      title: Data and System Architect
      started: 2013
      duration: (2013 - Now)
      projects:
        - project1:
          name: Uniform Publishing Platform 
          description: Using the uniform publish interface for all kinds of clients, and there is a data discovery interface.
        - project2:
          name: Upgrade VIP System
          description: Optimize the VIP system architecture. Slice the databases and tables. Using the micro-service to improve the flexibility. Enhance the system monitor and warning.
        - project3:
          name: Smart Operation System
          description: The original operation system of iqiyi.com uses manual editing mode. It was inefficient, but the new smart operation system cat improve editor’s efficiency by intelligent video analysis and machine learning. 
        - project4:
          name: Pages Compile System
          description: The web pages in iqiyi.com publishing needs to be compiled into static pages to let users quickly access. The original system had the low performance, and couldn’t use the resource effectively. Upgrading the system architecture, using multiple queues to improve performance and resource utilization.
        - project5:
          name: Pages Publishing System
          description: iqiyi.com UGC(User Generate Content) uses pseudo-static pages, dynamically generated pages in the background, generating a fixed URL by URL rewrite when the page is displayed. Page content generating need to call multiple internal interfaces, using a multi-threaded concurrent framework which implemented myself to improve performance.
    - work2:
      company: IBM
      department: China Development Lab (CDL)
      section: Information Management
      location: Beijing
      title: Software Engineer
      started: 2005
      duration: (2005 - 2013)
      description: 
      projects:
        - project1:
          name: IBM Data Studio
          description: IBM Data Studio provides an integrated, modular environment for database development and administration of IBM DB2 for Linux, UNIX and Windows. It also offers collaborative database development tools for IBM DB2 for z/OS, IBM DB2 for i, and IBM Informix. This software is available at no charge. IBM Data Studio enables developers and administrators to create and manage heterogeneous database environments for increased productivity.
        - project2:
          name: IBM Smart Analytics System
          description: The IBM Smart Analytics System is an integrated platform that provides broad analytics capabilities on a powerful warehouse foundation with IBM server and storage. Deeply integrated and optimized, IBM Smart Analytics System provides a single point of support for end-to-end analytics solutions.
        - project3:
          name: IBM PureApplication System
          description: Cloud application deployment normally requires scripting and configuring the tasks to deploy and manage an application, its environment and the underlying infrastructure. IBM® PureApplication® simplifies and automates this process for both on-premises and off-premises cloud options.
        - project3:
          name: Optim Query Tuner
          description: Optim Query Tuner for DB2 for z/OS and Optim Query Tuner for DB2 for Linux, UNIX and Windows cuts cost and improves performance by providing expert advice on writing high quality queries and improving database design. It’s easy-to-use advisors can help developers to write more efficient SQL queries.
        - project4:
          name: Optim Performance Manager
          description: Optim Performance Manager provides a Web interface that you can use to isolate and analyze typical database performance problems. You can view a summary of the health of your databases and drill down for more details. It provides Preconfigured alerts, Health summary view of all monitored databases, Dashboards for drilling down to view specific types of problems for a database.
  educations:
    - education1:
      organization: Peking University, China
      school: School of Software and Microelectronics
      degree: Master
      major: Software Engineering
      started: 2004
      duration: (2004 - 2007)
      description: 
    - education2:
      organization: Huazhong University of Science and Technology, China
      school: Collage of Electrical and Electronic Engineering
      degree: Bachelor
      major: Electrical Engineering and Automation
      started: 1999
      duration: (1999 - 2003)
      description: 
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmings:
    - skill1:
      name: Java
      percentage: 80%
      description: The first programming language in production. Familiar with JVM memory model and GC policy. Read the virtual machine specification and researched the concurrency and I/O parts. Rich experience in Java Web, and read parts of the Spring and Hibernate source code.
    - skill2:
      name: JavaScript 
      percentage: 80%
      description: The second programming language in production. Familiar with javascript native API but not the popular front-end framework. Known about how the web browser working. Could use the popular frameworks and libraries skillfully. Some experience about the Node.JS.
    - skill3:
      name: HTML, CSS
      percentage: 70%
      description: Used for data visualization, known about the basic HTML element's semantics and CSS selector, position, box model, transform, transition etc.
    - skill4:
      name: GPGPU - CUDA, OpenCL
      percentage: 90%
      description: Familiar with GPU programming model, basic interface and performance optimization. Experience in OpenCL is more than CUDA.
    - skill5:
      name: C/C++
      percentage: 60%
      description: Used in GPU programming as host language. Known about GNU gcc compiling. Writing Makefile and CMake. Some experience about OpenCV and ffmpeg.
    - skill6:
      name: Python
      percentage: 70%
      description: Used as system script and data analytic tools. Familiar with common API, but need to read documentation for details.
    - skill7:
      name: Ruby
      percentage: 50%
      description: Used in Vagrant, Chef and Puppet configuration script. Some experience in Rails.
    - skill8:
      name: Scala
      percentage: 50%
      description: Used in Spark. Known about common API and language grammar. Functional programming.
    - skill9:
      name: Groovy
      percentage: 40%
      description: Used in some dynamic language scenario, just used in some project, didn't know the detail.
  developments:
    - skill1:
      name: Data Visualization
      percentage: 90%
      description: Rich experience on it. Have the management background, can summarize the data model by business model. Base on the requirement and using my technology stack to implement the data visualization form end to end.
    - skill2:
      name: Machine Learning
      percentage: 70%
      description: Familiar with the common algorithm, implemented the Naive Bayes, Linear Regression, Random Forest and kNN. Can using the Collaborative Filtering to build a recommender system. Used Theano, Caffe and learning TensorFlow and CNTK. Used Mahout and Spark ML in projects.
    - skill3:
      name: Parallel and Concurrent
      percentage: 80%
      description: Java concurrency, GPU SIMD, Functional programming and Actor pattern.
    - skill4:
      name: Hadoop
      percentage: 70%
      description: Known about HDFS, written the code about MapReduce. Configured Hadoop system and optimization, read parts of source code and implemented the TeraSort. Have some experience about HBase, Hive, Pig, Flume, Sqoop, etc.
    - skill5:
      name: Spark
      percentage: 60%
      description: Known about RDD. Configured Spark system, read parts if source code and implemented the TeraSort. Used MLlib module and Streaming module.
    - skill6:
      name: Mesos
      percentage: 40%
      description: Installation and configuration, used with Spark. Read the allocator part source code.
    - skill7:
      name: OpenStack
      percentage: 60%
      description: Installation and configuration, enhance Horizon and read parts of source code.
    - skill8:
      name: Docker
      percentage: 70%
      description: Have some experience about installing Kubernetes. Currently my personal development environment are all base on Vagrant or Docker. Written Dockerfile in docker hub.
    - skill9:
      name: Database
      percentage: 70%
      description: Have rich experience about database tools development in IBM. Configuration and optimization about MySQL, PostgreSQL and MongoDB.
  patents:
    - patent1:
      name: 数据处理方法及装置
      office: CN
      number: 201410415527
      publication: CN104199790A
    - patent2:
      name: 一种聚合页面中数据模块的方法及装置
      office: CN
      number: 201510541196
      publication: CN105159881A
    - patent3:
      name: 一种基于图像的用户动作标识区域确定方法及装置
      office: CN
      number: 201510146258
      publication: CN104700096A
    - patent4:
      name: 一种终端数据展现方法和系统
      office: CN
      number: 201510149300
      publication: CN104793933A
    - patent5:
      name: 一种浮点数处理方法及装置
      office: CN
      number: 201510629933
      publication: CN105224283A
    - patent6:
      name: 一种浮点数处理方法及装置
      office: CN
      number: 201510629934
      publication: CN105224284A
    - patent7:
      name: 多视角视频采集系统
      office: CN
      number: 201510727225
      publication: CN105407297A
